### ISSUE TITLE
Need to support GET requests for search

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/pystac-api-client#2]
Check if stac-api-spec requires POST for search, if so then client can just use POST for search, otherwise GET will need to be supported as well

**Comment by gadomski** [comment]
Per [stac-api-spec](https://github.com/radiantearth/stac-api-spec/blob/v1.0.0-beta.1/item-search/README.md#stac-api---item-search):

> Implementing GET /search is required, POST /search is optional, but recommended.
