### ISSUE TITLE
`simple_stac_resolver` does not handle requests properly

### ISSUE THREAD

**Issue by hamzaelsaawy** [stac-utils/pystac-api-client#23]
[`simple_stac_resolver`](https://github.com/stac-utils/pystac-api-client/blob/bc609956cc8f25b7c9ca0151e32ec38a86feb394/pystac_api/stac_io.py#L42) does not handle the  `original_request: requests.Requests` field correctly, accessing it like a dictionary with `original_request.get()` instead of using field access:
1. [`original_request.get('headers', {})`](https://github.com/stac-utils/pystac-api-client/blob/bc609956cc8f25b7c9ca0151e32ec38a86feb394/pystac_api/stac_io.py#L119)
2. [`original_request.get('json', {})`](https://github.com/stac-utils/pystac-api-client/blob/bc609956cc8f25b7c9ca0151e32ec38a86feb394/pystac_api/stac_io.py#L126)

Both cause the function to fail (taken from the docstrings, tested on python 3.8):
```
import json
import requests
from pystac_api.stac_io import simple_stac_resolver

original_request = requests.Request(
    method='POST',
    url='https://stac-api/search',
    data=json.dumps({'collections': ['my-collection']}).encode('utf-8'),
    headers={'x-custom-header': 'hi-there'}
)

next_link = {
     'href': 'https://stac-api/search?next=sometoken',
     'rel': 'next'
}

next_request = simple_stac_resolver(next_link, original_request)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-3727c92cfc17> in <module>
     14      'rel': 'next'
     15 }
---> 16 next_request = simple_stac_resolver(next_link, original_request)

/anaconda/envs/geo/lib/python3.8/site-packages/pystac_api/stac_io.py in simple_stac_resolver(link, original_request)
    117     # If the link object includes a "headers" property, use that and respect the "merge" property.
    118     link_headers = link.get('headers')
--> 119     headers = original_request.get('headers', {})
    120     if link_headers is not None:
    121         headers = {**headers, **link_headers} if merge else link_headers

AttributeError: 'Request' object has no attribute 'get'
```

**Comment by matthewhanson** [comment]
Hi @hamzaelsaawy thanks for posting on this and issuing a PR - I actually had this fixed in another branch I was working on.

This is still a bit of a work in progress - but we're looking to get it wrapped up and a 0.1.0 released to PyPi this week.
